export const movieActionTypes = {
  FETCH_UPCOMING_MOV: 'FETCH_UPCOMING_MOV',
  FETCH_POP_MOV: 'FETCH_POP_MOV',
  FETCH_UPCOMING_LIST: 'FETCH_UPCOMING_LIST',
  FETCH_POP_LIST: 'FETCH_POP_LIST',

  // SET_NOW_MOVIE: "SET_NOW_MOVIE",
  // SET_SEARCHED_MOVIES: "SET_SEARCHED_MOVIES",
};
